/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 40.0.0 Fri Dec 27 10:45:54 2024.
 */

#include <string.h>

#include "output_NodeA.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int output_NodeA_example_message1_pack(
    uint8_t *dst_p,
    const struct output_NodeA_example_message1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->speed, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->rpm, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->rpm, 8u, 0xffu);

    return (8);
}

int output_NodeA_example_message1_init(struct output_NodeA_example_message1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct output_NodeA_example_message1_t));

    return 0;
}

uint8_t output_NodeA_example_message1_speed_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

bool output_NodeA_example_message1_speed_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t output_NodeA_example_message1_rpm_encode(double value)
{
    return (uint16_t)(value);
}

bool output_NodeA_example_message1_rpm_is_in_range(uint16_t value)
{
    return (value <= 8000u);
}

int output_NodeA_example_message2_unpack(
    struct output_NodeA_example_message2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->voltage = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);

    return (0);
}

int output_NodeA_example_message2_init(struct output_NodeA_example_message2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct output_NodeA_example_message2_t));

    return 0;
}

double output_NodeA_example_message2_temperature_decode(uint8_t value)
{
    return ((double)value);
}

bool output_NodeA_example_message2_temperature_is_in_range(uint8_t value)
{
    return (value <= 215u);
}

double output_NodeA_example_message2_voltage_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool output_NodeA_example_message2_voltage_is_in_range(uint16_t value)
{
    return (value <= 6553u);
}
