/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 40.0.0 Fri Dec 27 10:45:54 2024.
 */

#ifndef OUTPUT_NODEA_H
#define OUTPUT_NODEA_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define OUTPUT_NODEA_EXAMPLE_MESSAGE1_FRAME_ID (0x64u)
#define OUTPUT_NODEA_EXAMPLE_MESSAGE2_FRAME_ID (0xc8u)

/* Frame lengths in bytes. */
#define OUTPUT_NODEA_EXAMPLE_MESSAGE1_LENGTH (8u)
#define OUTPUT_NODEA_EXAMPLE_MESSAGE2_LENGTH (4u)

/* Extended or standard frame types. */
#define OUTPUT_NODEA_EXAMPLE_MESSAGE1_IS_EXTENDED (0)
#define OUTPUT_NODEA_EXAMPLE_MESSAGE2_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define OUTPUT_NODEA_EXAMPLE_MESSAGE1_NAME "ExampleMessage1"
#define OUTPUT_NODEA_EXAMPLE_MESSAGE2_NAME "ExampleMessage2"

/* Signal Names. */
#define OUTPUT_NODEA_EXAMPLE_MESSAGE1_SPEED_NAME "Speed"
#define OUTPUT_NODEA_EXAMPLE_MESSAGE1_RPM_NAME "RPM"
#define OUTPUT_NODEA_EXAMPLE_MESSAGE2_TEMPERATURE_NAME "Temperature"
#define OUTPUT_NODEA_EXAMPLE_MESSAGE2_VOLTAGE_NAME "Voltage"

/**
 * Signals in message ExampleMessage1.
 *
 * This is an example message with Speed and RPM signals.
 *
 * All signal values are as on the CAN bus.
 */
struct output_NodeA_example_message1_t {
    /**
     * The speed of the vehicle in km/h.
     *
     * Range: 0..2500 (0..250 km/h)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t speed;

    /**
     * The engine revolutions per minute.
     *
     * Range: 0..8000 (0..8000 rpm)
     * Scale: 1
     * Offset: 0
     */
    uint16_t rpm;
};

/**
 * Signals in message ExampleMessage2.
 *
 * This is another example message with Temperature and Voltage signals.
 *
 * All signal values are as on the CAN bus.
 */
struct output_NodeA_example_message2_t {
    /**
     * Ambient temperature in Celsius.
     *
     * Range: -40..215 (-40..215 °C)
     * Scale: 1
     * Offset: 0
     */
    uint8_t temperature;

    /**
     * Battery voltage in Volts.
     *
     * Range: 0..6553 (0..65.535 V)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t voltage;
};

/**
 * Pack message ExampleMessage1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int output_NodeA_example_message1_pack(
    uint8_t *dst_p,
    const struct output_NodeA_example_message1_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ExampleMessage1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int output_NodeA_example_message1_init(struct output_NodeA_example_message1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t output_NodeA_example_message1_speed_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool output_NodeA_example_message1_speed_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t output_NodeA_example_message1_rpm_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool output_NodeA_example_message1_rpm_is_in_range(uint16_t value);

/**
 * Unpack message ExampleMessage2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int output_NodeA_example_message2_unpack(
    struct output_NodeA_example_message2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ExampleMessage2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int output_NodeA_example_message2_init(struct output_NodeA_example_message2_t *msg_p);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double output_NodeA_example_message2_temperature_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool output_NodeA_example_message2_temperature_is_in_range(uint8_t value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double output_NodeA_example_message2_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool output_NodeA_example_message2_voltage_is_in_range(uint16_t value);


#ifdef __cplusplus
}
#endif

#endif
